cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'cmake'
brew 'coreutils'
brew 'libgit2'
brew 'md5sha1sum'
brew 'openssl'
brew 'pyenv'
brew 'readline'
brew 'ripgrep'
brew 'shellcheck'
brew 'tmux'
brew 'unrar'
brew 'vim'
brew 'wget'

cask 'firefox'
cask 'google-chrome'
cask 'intellij-idea'
cask 'iterm2'
cask 'libreoffice'
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'vlc'
cask 'whatsapp'
