set nocompatible
filetype off

" Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" My Plugins
Plugin 'tpope/vim-fugitive'
Plugin 'bling/vim-airline'
Plugin 'derekwyatt/vim-scala'
Plugin 'plasticboy/vim-markdown'
" Plugin 'tpope/vim-surround'
Plugin 'kien/ctrlp.vim'
" Plugin 'fisadev/vim-ctrlp-cmdpalette'
Plugin 'kchmck/vim-coffee-script'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'ervandew/supertab'
Plugin 'terryma/vim-multiple-cursors'

call vundle#end()

set autoindent

" Redefine leader
let mapleader="<"
set showcmd

" Spaces for tab indents
set tabstop=4
set shiftwidth=4
set expandtab

autocmd FileType ruby setlocal shiftwidth=2 tabstop=2

" 80 characters margin and line numbers
set colorcolumn=80
set number
set showbreak=⇇

" Fix Backspace
set backspace=indent,eol,start

" Encoding
set encoding=utf-8
setglobal fileencoding=utf-8

" Navigation
set hidden
nmap <leader>l :bnext<CR>
nmap <leader>h :bprevious<CR>

" airline
set t_Co=256
set laststatus=2
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'

" Theme
" colors morning
colors summerfruit256

" multiple-cursor
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'

syntax on
filetype plugin indent on
