[theme]
mode              = "light"
builtin           = "Catppuccin"

[theme.templates]
enable_builtin_templates = true
builtin_ids              = ["ghostty", "niri"]

[templates]
community_ids = ["spicetify"]

[plugins]
enabled = ["davemhammer/tailscale"]
auto_update = "all"
